// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdomx6W3LZzqO0d4T80TerW-uE1s8IIQY',
    appId: '1:37699792350:web:8dd076e6a4f59f4093014f',
    messagingSenderId: '37699792350',
    projectId: 'geo-bin-sem4',
    authDomain: 'geo-bin-sem4.firebaseapp.com',
    storageBucket: 'geo-bin-sem4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClU1lLQIJtJyW9I7gvI7nrtzRyDxo6K-s',
    appId: '1:37699792350:android:c874dadfc8054b3f93014f',
    messagingSenderId: '37699792350',
    projectId: 'geo-bin-sem4',
    storageBucket: 'geo-bin-sem4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRkcf6X8OndpS4U1tygazvOpo2xJSFOCY',
    appId: '1:37699792350:ios:990f22a4e958523193014f',
    messagingSenderId: '37699792350',
    projectId: 'geo-bin-sem4',
    storageBucket: 'geo-bin-sem4.appspot.com',
    androidClientId: '37699792350-mk0rnv851bu8d4h6aipufme0kralrtd6.apps.googleusercontent.com',
    iosClientId: '37699792350-6kb06dhjfvupa1bmfkcmtke08g2a4fut.apps.googleusercontent.com',
    iosBundleId: 'com.example.geobin',
  );
}
